name: sshx 6 hours session

on:
  workflow_dispatch:

jobs:
  sshx:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: run sshx
        run: |
          curl -sSf https://sshx.io/get | sh -s run &
          echo "sshx started, keeping runner alive for 6 hours..."
          sleep 6h
